const colors = {
  light: {
    text: "#1A1F2E",
    tint: "#2563EB",
    background: "#F0F4FF",
    foreground: "#1A1F2E",
    card: "#FFFFFF",
    cardForeground: "#1A1F2E",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    primaryLight: "#EEF4FF",
    secondary: "#7C3AED",
    secondaryForeground: "#FFFFFF",
    secondaryLight: "#F3EEFF",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#0EA5E9",
    accentForeground: "#FFFFFF",
    accentLight: "#E0F6FF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    destructiveLight: "#FEE2E2",
    border: "#E2E8F0",
    input: "#E2E8F0",
    success: "#10B981",
    successForeground: "#FFFFFF",
    successBg: "#D1FAE5",
    warning: "#F59E0B",
    warningBg: "#FEF3C7",
    errorBg: "#FEE2E2",
    surplusBg: "#D1FAE5",
    shadow: "rgba(37, 99, 235, 0.10)",
    headerGradientStart: "#1E40AF",
    headerGradientEnd: "#2563EB",
  },
  radius: 14,
};
export default colors;
